-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 20:32:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nutriapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nutriapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nutriapp` DEFAULT CHARACTER SET utf8 ;
USE `nutriapp` ;

-- -----------------------------------------------------
-- Table `nutriapp`.`proteina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`proteina` (
  `idproteina` INT NOT NULL AUTO_INCREMENT,
  `nombre_proteina` VARCHAR(100) NOT NULL,
  `porcion_proteina` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idproteina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`grasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`grasa` (
  `idgrasas` INT NOT NULL AUTO_INCREMENT,
  `nombre_grasa` VARCHAR(100) NOT NULL,
  `porcion_grasa` VARCHAR(100) NOT NULL,
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idgrasas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`verdura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`verdura` (
  `idverdura` INT NOT NULL AUTO_INCREMENT,
  `nombre_verdura` VARCHAR(100) NOT NULL,
  `porcion_verdura` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idverdura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`cereal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`cereal` (
  `idcereal` INT NOT NULL AUTO_INCREMENT,
  `nombre_cereal` VARCHAR(100) NOT NULL,
  `porcion_cereal` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcereal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`leguminosa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`leguminosa` (
  `idleguminosa` INT NOT NULL AUTO_INCREMENT,
  `nombre_leguminosa` VARCHAR(100) NOT NULL,
  `porcion_leguminosa` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idleguminosa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`lacteo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`lacteo` (
  `idlacteo` INT NOT NULL AUTO_INCREMENT,
  `nombre_lacteo` VARCHAR(100) NOT NULL,
  `porcion_lacteo` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlacteo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`fruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`fruta` (
  `idfruta` INT NOT NULL AUTO_INCREMENT,
  `nombre_fruta` VARCHAR(100) NOT NULL,
  `porcion_fruta` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idfruta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nivel_rol` VARCHAR(75) NOT NULL,
  `activo` TINYINT NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(75) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idroles` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_roles1_idx` (`fk_idroles` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`fk_idroles`)
    REFERENCES `nutriapp`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`almuerzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`almuerzo` (
  `idalmuerzo` INT NOT NULL AUTO_INCREMENT,
  `hora_armuerzo` TIME NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idproteina` INT NOT NULL,
  `fk_idgrasas` INT NOT NULL,
  `fk_idverdura` INT NOT NULL,
  `fk_idcereal` INT NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idalmuerzo`),
  INDEX `fk_almuerzo_proteina1_idx` (`fk_idproteina` ASC) VISIBLE,
  INDEX `fk_almuerzo_grasa1_idx` (`fk_idgrasas` ASC) VISIBLE,
  INDEX `fk_almuerzo_verdura1_idx` (`fk_idverdura` ASC) VISIBLE,
  INDEX `fk_almuerzo_cereal1_idx` (`fk_idcereal` ASC) VISIBLE,
  INDEX `fk_almuerzo_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_almuerzo_proteina1`
    FOREIGN KEY (`fk_idproteina`)
    REFERENCES `nutriapp`.`proteina` (`idproteina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almuerzo_grasa1`
    FOREIGN KEY (`fk_idgrasas`)
    REFERENCES `nutriapp`.`grasa` (`idgrasas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almuerzo_verdura1`
    FOREIGN KEY (`fk_idverdura`)
    REFERENCES `nutriapp`.`verdura` (`idverdura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almuerzo_cereal1`
    FOREIGN KEY (`fk_idcereal`)
    REFERENCES `nutriapp`.`cereal` (`idcereal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_almuerzo_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`comida` (
  `idcomida` INT NOT NULL AUTO_INCREMENT,
  `hora_comida` TIME NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idgrasas` INT NOT NULL,
  `fk_idproteina` INT NOT NULL,
  `fk_idverdura` INT NOT NULL,
  `fk_idcereal` INT NOT NULL,
  `fk_idleguminosa` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcomida`),
  INDEX `fk_comida_grasa1_idx` (`fk_idgrasas` ASC) VISIBLE,
  INDEX `fk_comida_proteina1_idx` (`fk_idproteina` ASC) VISIBLE,
  INDEX `fk_comida_verdura1_idx` (`fk_idverdura` ASC) VISIBLE,
  INDEX `fk_comida_cereal1_idx` (`fk_idcereal` ASC) VISIBLE,
  INDEX `fk_comida_leguminosa1_idx` (`fk_idleguminosa` ASC) VISIBLE,
  INDEX `fk_comida_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_comida_grasa1`
    FOREIGN KEY (`fk_idgrasas`)
    REFERENCES `nutriapp`.`grasa` (`idgrasas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_proteina1`
    FOREIGN KEY (`fk_idproteina`)
    REFERENCES `nutriapp`.`proteina` (`idproteina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_verdura1`
    FOREIGN KEY (`fk_idverdura`)
    REFERENCES `nutriapp`.`verdura` (`idverdura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_cereal1`
    FOREIGN KEY (`fk_idcereal`)
    REFERENCES `nutriapp`.`cereal` (`idcereal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_leguminosa1`
    FOREIGN KEY (`fk_idleguminosa`)
    REFERENCES `nutriapp`.`leguminosa` (`idleguminosa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`tipo_cena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`tipo_cena` (
  `idtipo_cena` INT NOT NULL AUTO_INCREMENT,
  `nombre_cena` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idtipo_cena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`cena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`cena` (
  `idcena` INT NOT NULL AUTO_INCREMENT,
  `hora_cena` TIME NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idtipo_cena` INT NOT NULL,
  `fk_idcereal` INT NULL,
  `fk_idlacteo` INT NULL,
  `fk_idverdura` INT NULL,
  `fk_idproteina` INT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcena`),
  INDEX `fk_cena_tipo_cena_idx` (`fk_idtipo_cena` ASC) VISIBLE,
  INDEX `fk_cena_cereal1_idx` (`fk_idcereal` ASC) VISIBLE,
  INDEX `fk_cena_lacteo1_idx` (`fk_idlacteo` ASC) VISIBLE,
  INDEX `fk_cena_verdura1_idx` (`fk_idverdura` ASC) VISIBLE,
  INDEX `fk_cena_proteina1_idx` (`fk_idproteina` ASC) VISIBLE,
  INDEX `fk_cena_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_cena_tipo_cena`
    FOREIGN KEY (`fk_idtipo_cena`)
    REFERENCES `nutriapp`.`tipo_cena` (`idtipo_cena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cena_cereal1`
    FOREIGN KEY (`fk_idcereal`)
    REFERENCES `nutriapp`.`cereal` (`idcereal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cena_lacteo1`
    FOREIGN KEY (`fk_idlacteo`)
    REFERENCES `nutriapp`.`lacteo` (`idlacteo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cena_verdura1`
    FOREIGN KEY (`fk_idverdura`)
    REFERENCES `nutriapp`.`verdura` (`idverdura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cena_proteina1`
    FOREIGN KEY (`fk_idproteina`)
    REFERENCES `nutriapp`.`proteina` (`idproteina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cena_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`colacion_uno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`colacion_uno` (
  `idcolacion_uno` INT NOT NULL AUTO_INCREMENT,
  `hora_colacion` TIME NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_idfruta` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcolacion_uno`),
  INDEX `fk_colacion_uno_fruta1_idx` (`fk_idfruta` ASC) VISIBLE,
  INDEX `fk_colacion_uno_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_colacion_uno_fruta1`
    FOREIGN KEY (`fk_idfruta`)
    REFERENCES `nutriapp`.`fruta` (`idfruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colacion_uno_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`colacion_dos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`colacion_dos` (
  `idcolacion_dos` INT NOT NULL AUTO_INCREMENT,
  `hora_colacion` TIME NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fruta_idfruta` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcolacion_dos`),
  INDEX `fk_colacion_dos_fruta1_idx` (`fruta_idfruta` ASC) VISIBLE,
  INDEX `fk_colacion_dos_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_colacion_dos_fruta1`
    FOREIGN KEY (`fruta_idfruta`)
    REFERENCES `nutriapp`.`fruta` (`idfruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colacion_dos_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`desayuno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`desayuno` (
  `iddesayuno` INT NOT NULL AUTO_INCREMENT,
  `tipo_desayuno` VARCHAR(70) NOT NULL,
  `descripcion_desayuno` VARCHAR(150) NOT NULL,
  `hora_desayuno` TIME NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`iddesayuno`),
  INDEX `fk_desayuno_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_desayuno_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`dieta_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`dieta_dia` (
  `iddieta_dia` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddesayuno` INT NOT NULL,
  `fk_idalmuerzo` INT NOT NULL,
  `fk_idcolacion_uno` INT NOT NULL,
  `fk_idcomida` INT NOT NULL,
  `fk_idcolacion_dos` INT NOT NULL,
  `fk_idcena` INT NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iddieta_dia`),
  INDEX `fk_dieta_dia_desayuno1_idx` (`fk_iddesayuno` ASC) VISIBLE,
  INDEX `fk_dieta_dia_almuerzo1_idx` (`fk_idalmuerzo` ASC) VISIBLE,
  INDEX `fk_dieta_dia_colacion_uno1_idx` (`fk_idcolacion_uno` ASC) VISIBLE,
  INDEX `fk_dieta_dia_comida1_idx` (`fk_idcomida` ASC) VISIBLE,
  INDEX `fk_dieta_dia_colacion_dos1_idx` (`fk_idcolacion_dos` ASC) VISIBLE,
  INDEX `fk_dieta_dia_cena1_idx` (`fk_idcena` ASC) VISIBLE,
  INDEX `fk_dieta_dia_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_dieta_dia_desayuno1`
    FOREIGN KEY (`fk_iddesayuno`)
    REFERENCES `nutriapp`.`desayuno` (`iddesayuno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_almuerzo1`
    FOREIGN KEY (`fk_idalmuerzo`)
    REFERENCES `nutriapp`.`almuerzo` (`idalmuerzo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_colacion_uno1`
    FOREIGN KEY (`fk_idcolacion_uno`)
    REFERENCES `nutriapp`.`colacion_uno` (`idcolacion_uno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_comida1`
    FOREIGN KEY (`fk_idcomida`)
    REFERENCES `nutriapp`.`comida` (`idcomida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_colacion_dos1`
    FOREIGN KEY (`fk_idcolacion_dos`)
    REFERENCES `nutriapp`.`colacion_dos` (`idcolacion_dos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_cena1`
    FOREIGN KEY (`fk_idcena`)
    REFERENCES `nutriapp`.`cena` (`idcena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dieta_dia_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`dieta` (
  `iddieta` INT NOT NULL AUTO_INCREMENT,
  `nombre_dieta` VARCHAR(100) NOT NULL,
  `semanas_dieta` INT NOT NULL,
  PRIMARY KEY (`iddieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`lunes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`lunes` (
  `idlunes` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idlunes`),
  INDEX `fk_lunes_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_lunes_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_lunes_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lunes_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`martes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`martes` (
  `idmartes` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idmartes`),
  INDEX `fk_martes_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_martes_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_martes_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_martes_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`miercoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`miercoles` (
  `idmiercoles` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idmiercoles`),
  INDEX `fk_miercoles_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_miercoles_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_miercoles_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miercoles_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`jueves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`jueves` (
  `idjueves` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idjueves`),
  INDEX `fk_jueves_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_jueves_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_jueves_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jueves_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`viernes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`viernes` (
  `idviernes` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idviernes`),
  INDEX `fk_viernes_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_viernes_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_viernes_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viernes_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`sabado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`sabado` (
  `idsabado` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusarios` INT NOT NULL,
  PRIMARY KEY (`idsabado`),
  INDEX `fk_sabado_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_sabado_usuarios1_idx` (`fk_idusarios` ASC) VISIBLE,
  CONSTRAINT `fk_sabado_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sabado_usuarios1`
    FOREIGN KEY (`fk_idusarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`domingo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`domingo` (
  `iddomingo` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_iddieta_dia` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`iddomingo`),
  INDEX `fk_domingo_dieta_dia1_idx` (`fk_iddieta_dia` ASC) VISIBLE,
  INDEX `fk_domingo_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_domingo_dieta_dia1`
    FOREIGN KEY (`fk_iddieta_dia`)
    REFERENCES `nutriapp`.`dieta_dia` (`iddieta_dia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domingo_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`semana` (
  `idsemana` INT NOT NULL AUTO_INCREMENT,
  `fk_iddieta` INT NOT NULL,
  `fk_idlunes` INT NOT NULL,
  `fk_idmartes` INT NOT NULL,
  `fk_idmiercoles` INT NOT NULL,
  `fk_idjueves` INT NOT NULL,
  `fk_idviernes` INT NOT NULL,
  `fk_idsabado` INT NOT NULL,
  `fk_iddomingo` INT NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idsemana`),
  INDEX `fk_semana_dieta1_idx` (`fk_iddieta` ASC) VISIBLE,
  INDEX `fk_semana_lunes1_idx` (`fk_idlunes` ASC) VISIBLE,
  INDEX `fk_semana_martes1_idx` (`fk_idmartes` ASC) VISIBLE,
  INDEX `fk_semana_miercoles1_idx` (`fk_idmiercoles` ASC) VISIBLE,
  INDEX `fk_semana_jueves1_idx` (`fk_idjueves` ASC) VISIBLE,
  INDEX `fk_semana_viernes1_idx` (`fk_idviernes` ASC) VISIBLE,
  INDEX `fk_semana_sabado1_idx` (`fk_idsabado` ASC) VISIBLE,
  INDEX `fk_semana_domingo1_idx` (`fk_iddomingo` ASC) VISIBLE,
  INDEX `fk_semana_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_semana_dieta1`
    FOREIGN KEY (`fk_iddieta`)
    REFERENCES `nutriapp`.`dieta` (`iddieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_lunes1`
    FOREIGN KEY (`fk_idlunes`)
    REFERENCES `nutriapp`.`lunes` (`idlunes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_martes1`
    FOREIGN KEY (`fk_idmartes`)
    REFERENCES `nutriapp`.`martes` (`idmartes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_miercoles1`
    FOREIGN KEY (`fk_idmiercoles`)
    REFERENCES `nutriapp`.`miercoles` (`idmiercoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_jueves1`
    FOREIGN KEY (`fk_idjueves`)
    REFERENCES `nutriapp`.`jueves` (`idjueves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_viernes1`
    FOREIGN KEY (`fk_idviernes`)
    REFERENCES `nutriapp`.`viernes` (`idviernes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_sabado1`
    FOREIGN KEY (`fk_idsabado`)
    REFERENCES `nutriapp`.`sabado` (`idsabado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_domingo1`
    FOREIGN KEY (`fk_iddomingo`)
    REFERENCES `nutriapp`.`domingo` (`iddomingo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semana_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`seguimiento` (
  `idseguimiento` INT NOT NULL AUTO_INCREMENT,
  `cumplimiento` TINYINT NOT NULL,
  `peso_inicial` VARCHAR(45) NOT NULL,
  `peso_final` VARCHAR(45) NOT NULL,
  `fk_iddieta` INT NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  `uuid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idseguimiento`),
  INDEX `fk_seguimiento_dieta1_idx` (`fk_iddieta` ASC) VISIBLE,
  INDEX `fk_seguimiento_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_seguimiento_dieta1`
    FOREIGN KEY (`fk_iddieta`)
    REFERENCES `nutriapp`.`dieta` (`iddieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguimiento_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`fruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`fruta` (
  `idfruta` INT NOT NULL AUTO_INCREMENT,
  `nombre_fruta` VARCHAR(100) NOT NULL,
  `porcion_fruta` VARCHAR(100) NOT NULL,
  `fecha_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idfruta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_modulo` VARCHAR(100) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`submodulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`submodulo` (
  `idsubmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_submodulo` VARCHAR(100) NOT NULL,
  `ruta` VARCHAR(100) NOT NULL,
  `activo` TINYINT NOT NULL,
  `fk_idmodulo` INT NOT NULL,
  PRIMARY KEY (`idsubmodulo`),
  INDEX `fk_submodulo_modulo1_idx` (`fk_idmodulo` ASC) VISIBLE,
  CONSTRAINT `fk_submodulo_modulo1`
    FOREIGN KEY (`fk_idmodulo`)
    REFERENCES `nutriapp`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`permisos` (
  `idpermisos` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT NOT NULL,
  `fk_idroles` INT NOT NULL,
  `fk_idmodulo` INT NOT NULL,
  `fk_idsubmodulo` INT NOT NULL,
  PRIMARY KEY (`idpermisos`),
  INDEX `fk_permisos_roles1_idx` (`fk_idroles` ASC) VISIBLE,
  INDEX `fk_permisos_modulo1_idx` (`fk_idmodulo` ASC) VISIBLE,
  INDEX `fk_permisos_submodulo1_idx` (`fk_idsubmodulo` ASC) VISIBLE,
  CONSTRAINT `fk_permisos_roles1`
    FOREIGN KEY (`fk_idroles`)
    REFERENCES `nutriapp`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisos_modulo1`
    FOREIGN KEY (`fk_idmodulo`)
    REFERENCES `nutriapp`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisos_submodulo1`
    FOREIGN KEY (`fk_idsubmodulo`)
    REFERENCES `nutriapp`.`submodulo` (`idsubmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutriapp`.`caracteristicas_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutriapp`.`caracteristicas_usuario` (
  `idcaracteristicas_usuario` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento` DATE NOT NULL,
  `estatura` INT NOT NULL,
  `peso_usuario` INT NOT NULL,
  `fk_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcaracteristicas_usuario`),
  INDEX `fk_caracteristicas_usuario_usuarios1_idx` (`fk_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_caracteristicas_usuario_usuarios1`
    FOREIGN KEY (`fk_idusuarios`)
    REFERENCES `nutriapp`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
